import os

print("Welcome to WinDebloater! Press Enter to start the debloat...")
input()
def bloatware_uninstall():
    os.system("Get-AppxPackage Microsoft.Microsoft3DViewer | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.BingWeather | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.GetHelp | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.WindowsMaps | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.YourPhone | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.XboxApp | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.MixedReality.Portal | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.SkypeApp | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.WindowsFeedbackHub | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage")
    os.system("Get-AppxPackage SpotifyAB.SpotifyMusic | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.Getstarted | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.MicrosoftStickyNotes | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.Office.OneNote | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.MicrosoftOfficeHub | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.MSPaint | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.WindowsSoundRecorder | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.People | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.WindowsCalculato | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.Windows.PeopleExperienceHost | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.Todos | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.PowerAutomateDesktop | Remove-AppxPackage")
    os.system("Get-AppxPackage Microsoft.BingNews | Remove-AppxPackage")
    os.system("Get-AppxPackage Clipchamp.Clipchamp | Remove-AppxPackage")
bloatware_uninstall()
os.system("power_plan.bat")